version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: beacon-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: beacon-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 15s
      timeout: 10s
      retries: 8
    restart: unless-stopped

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    container_name: beacon-kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c"]
    command: >
      kafka-topics --create --if-not-exists
      --topic official-accountability-events
      --bootstrap-server kafka:9092
      --partitions 6
      --replication-factor 1 &&
      echo "Kafka topics ready" &&
      sleep 2
    restart: "no"

  frontend:
    build:
      context: ./ui/react-native
    container_name: beacon-frontend
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  rest:
    build:
      context: ./backend/rest-service
    container_name: beacon-rest
    environment:
      - JAVA_OPTS=
    ports:
      - "8081:8080"
    restart: unless-stopped

  sse:
    build:
      context: ./backend/sse-service
    container_name: beacon-sse
    environment:
      - JAVA_OPTS=
    ports:
      - "8082:8080"
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: beacon-nginx
    depends_on:
      - frontend
      - rest
      - sse
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    restart: unless-stopped

  ingest-usa-fed:
    build:
      context: .
      dockerfile: services/ingest-usa-fed/Dockerfile
    container_name: ingest-usa-fed
    depends_on:
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CONGRESS_BASE_URL=https://api.congress.gov/v3
      - CONGRESS_API_KEY=${CONGRESS_API_KEY:-demo-api-key}
      - CONGRESS_POLL_INTERVAL=PT5M
      - CONGRESS_DEFAULT_CHAMBER=Senate
    restart: unless-stopped
