version: "3.9"

services:
  frontend:
    build:
      context: ./ui/react-native
    container_name: beacon-frontend
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  rest:
    build:
      context: ./backend/rest-service
    container_name: beacon-rest
    environment:
      - JAVA_OPTS=
    ports:
      - "8081:8080"
    restart: unless-stopped

  sse:
    build:
      context: ./backend/sse-service
    container_name: beacon-sse
    environment:
      - JAVA_OPTS=
    ports:
      - "8082:8080"
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: beacon-nginx
    depends_on:
      - frontend
      - rest
      - sse
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    restart: unless-stopped
