package com.beacon.ingest.usafed.llm;

/**
 * Contract for services capable of issuing prompts to large language models.
 */
public interface LlmClient {

    /**
     * Sends the supplied prompt to the specified {@link Model} and returns the raw response content.
     *
     * @param model model selection used when dispatching the request
     * @param prompt natural language prompt to evaluate
     * @return textual response generated by the LLM (never {@code null})
     */
    String promptModel(Model model, String prompt);
}
